### ISSUE TITLE
NPE when create 'default' ConnectionFactoryFactory

### ISSUE THREAD

**Issue by zsigmond-czine-everit** [everit-org/jetty-server-component#13]
```
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|java.lang.NullPointerException
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at java.util.Objects.requireNonNull(Objects.java:203)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at java.util.Arrays.asList(Arrays.java:3800)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.HttpConnectionFactoryFactoryComponent.createConnectionFactory(HttpConnectionFactoryFactoryComponent.java:133)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.ServerConnectorFactoryComponent.generateConnectionFactories(ServerConnectorFactoryComponent.java:148)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.ServerConnectorFactoryComponent.createNetworkConnector(ServerConnectorFactoryComponent.java:123)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.ServerConnectorFactoryComponent.createNetworkConnector(ServerConnectorFactoryComponent.java:53)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.JettyServerComponent.addNewConnectors(JettyServerComponent.java:268)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.JettyServerComponent.updateConnectorFactoriesOnServer(JettyServerComponent.java:424)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.jetty.server.component.internal.JettyServerComponent.activate(JettyServerComponent.java:245)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at java.lang.reflect.Method.invoke(Method.java:498)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.ecm.component.ri.internal.ActivateMethodHelper.call(ActivateMethodHelper.java:161)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.starting(ComponentContextImpl.java:747)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.updateConfigurationInLock(ComponentContextImpl.java:871)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.updateConfiguration(ComponentContextImpl.java:842)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.everit.osgi.ecm.component.ri.internal.FactoryComponentContainerImpl.updated(FactoryComponentContainerImpl.java:139)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.apache.felix.cm.impl.helper.ManagedServiceFactoryTracker.provideConfiguration(ManagedServiceFactoryTracker.java:88)
FINEST|3024/0|equinoxtest|16-05-30 12:41:52|    at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1744)
FINEST|3024/0|equinoxtest|16-05-30 12:41:53|    at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:103)
FINEST|3024/0|equinoxtest|16-05-30 12:41:53|    at java.lang.Thread.run(Thread.java:745)
```

**Comment by balazs-zsoldos** [comment]
Following this in #14 as stacktrace is more recent there
